### ISSUE TITLE
Upcoming Community Standup stream has incorrect date/time, no GitHub issue for questions

### ISSUE THREAD

**Issue by riverar** [microsoft/ProjectReunion#106]
Stream: https://www.youtube.com/watch?v=50PGkfLNDoQ

Suggest creating a GitHub issue for questions, a la WinUI.

**Comment by riverar** [comment]
Update: Steam now reflects the correct date/time.

**Comment by stevewri** [comment]
Ah, I think I see the ask. @mevey, if you look at the WinUI repo, there's a pinned issue for the July WinUI Community Call. Since the subject for this week's WinUI call is Reunion, we should have a similar pinned issue letting Reunion folks know about the upcoming call and pointing them to the details at the WinUI issue. Can you work with @anawishnoff to set that up Monday?

**Comment by mevey** [comment]
There are two community calls this week. Learn more here https://github.com/microsoft/ProjectReunion/issues/110
