### ISSUE TITLE
Question: limitations on current speech recognition APIs

### ISSUE THREAD

**Issue by tomzorz** [microsoft/ProjectReunion#107]
Hi everyone

I have a project where the UWP speech recognition APIs came up, but I ran into a bunch of unexpected limitations:
 * There’s no way to do speech recognition on a custom stream or audio file (the API seems to just use the default recording device)
 * The continuous speech recognition session stops with a “UserCanceled” reason whenever the window loses focus / gets deactivated, which in a desktop environment is highly anti-productive – I can’t take notes, or look at anything else while using the app

Are there any plans for improvements in the area, or maybe workarounds for the issues I mentioned above? 

Per @ptorr-msft 's suggestion to solve the 2nd issue I tried enabling backgroundVOIP/VOIP capabilities, that didn't help. I also tried earlier running in a full trust WPF application - the results were the same. 

The old System.Speech API doesn’t have any of the issues above, but its quality is comparatively horrible based on my testing. Maybe with project reunion we could converge the two, best of both worlds?

**Comment by trrwilson** [comment]
Hello, @tomzorz ! I'm with the Speech SDK team and comment a bit here. Many thanks for the fantastic feedback and the interest in our speech technology.

Totally understood when you talk about the functional limitations that `Windows.Media.SpeechRecognition` has relative to `System.Speech` and, assuming you're referring to the accuracy difference with the "comparatively horrible" assessment, equally understood about `System.Speech` not being as good as its successor.

Our latest investments in speech recognition (and quite a few related areas) are included in the Azure Speech SDK, which has a landing page here: http://aka.ms/speech/sdk. This SDK is made to work across a really wide range of operating systems, architectures, and environments; UWP in Windows is certainly one of them. It's not yet all the way there to that "best of both worlds" you mention, but it's growing rapidly and we'd love to hear your feedback on the SDK GitHub project here: https://github.com/Azure-Samples/cognitive-services-speech-sdk.

We're still actively working on plans for how we can fold this functionality back into Windows in a way that's appropriate for successorship to the APIs you've tried--but the Speech SDK project will for sure have the latest and greatest.

**Comment by tomzorz** [comment]
Hi @trrwilson - thanks for the reply! 

I do see that most speech recognition improvements happen in the cloud - and while I understand the upsides I think there are two critical issues: cost and developer effort. 

**Cost**

After 5 hours OR just wanting 2 concurrent users the free tier is already out of the question, now we're in $1/h territory.

**Developer effort**

After reading more into the docs, even if I get a paid instance it only supports up to 20 concurrent users - if I want more I need to deploy instances of this speech service to kubernetes? Also I guess I'd need to manage these? So suddenly I need to become a kubernetes expert and a devops person, because more than 20 people might want to e.g. take voice notes in my simple app. This seems like a gigantic effort that's not worth it for 99% of use-cases in my opinion, not to mention the whole system we'd need to set up to allow us tracking the costs of using the service and billing those to the actual users.

---

The new APIs are already a good successor for many simple use-cases, and I just hope there's a way to remove these arbitrary restrictions, instead of forcing this into a new revenue stream for Azure. Advanced use-cases, like custom vocabularies or multi-platform solutions will go with the cloud either way - in my view these restrictions on the `Windows.Media.SpeechRecognition` APIs only stop the "one-person-dev-team" from adding voice.

**Comment by stevewri** [comment]
We're discussing Reunion and cloud-based speech reco with the right teams and will work to make sure we have Reunion APIs in the future.

**Comment by trrwilson** [comment]
@tomzorz apologies that I missed replying to this until I saw the closure! If you haven't already, please bring questions about the Speech SDK and services it uses over to the GitHub issues list that's dedicated to it: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues

There are a variety of good solutions to many of the problems you mention--concurrency limits can be adjusted by the support team (20 is just the default and we have many customers running subscriptions with tens or even hundreds of times that concurrency limit regularly), silence/empty audio won't get billed at the same way (and traffic can be minimized from the device with good implementation strategies), and we do have existing custom speech capabilities for vocabulary that are becoming continually easier to use.

All that said, there are for sure use cases where it's not as easy as a built-in API like you've seen with `Windows.Media.SpeechRecognition` -- and I'd agree with you that the barrier to entry is higher today with the newest solutions. We'd love to get your feedback on items like this over in our issues so we can continue to refine the capabilities and -- getting this back on topic for Reunion -- make sure we're aligning our long-term strategy to what we'd make into a more direct replacement for what's been on Windows.

**Comment by livioenrico** [comment]
- Starting from the beginning of April 2023, the online speech dictation has stopped responding on Windows 10 systems worldwide. Tests have been conducted in numerous countries, including Europe, China, and India, and you can verify it on your own PC in just a few seconds by pressing the WINDOWS - H keys.

- It would be advisable for Microsoft to issue an official statement and encourage its users to be patient while the problem is being resolved. Currently, millions of users are following incorrect advice, such as reinstalling the microphone driver, doing a clean restart, or modifying the system registry. And many users have even reinstalled Windows without success.

**Comment by livioenrico** [comment]
- We have dedicated a lot of time to the development of the Theremino GPT application, which allows people with various disabilities, including the blind, to use the PC through voice commands.

- Until a few days ago, these users could use Skype to call their relatives, control home devices, or have friendly conversations with an assistant who could understand their difficulties and find appropriate solutions.

- Currently, these users, who are already facing many difficulties, have been left to themselves due to the failure to repair the online voice dictation server.

- We are disappointed that Microsoft has not been able to solve the problem after more than ten days.

- Please let us know if we can still rely on these functions, otherwise we will be forced to consider alternatives such as Google Speech Recognition.
