### ISSUE TITLE
Metadata for AppxPackaging API

### ISSUE THREAD

**Issue by mcooley** [microsoft/ProjectReunion#136]
# Proposal: Create a metadata-based API for AppxPackaging

## Summary
The [AppxPackaging API](https://docs.microsoft.com/en-us/windows/win32/appxpkg/interfaces) is an existing COM-based API for reading and modifying MSIX packages.

As a maintainer of some C# tools that process MSIX packages, I needed to write a significant amount of boilerplate code to call these APIs. These APIs would be easier to consume if they had WinRT metadata available, so a usable C# projection could be generated automatically.

## Rationale
* Make it easier to build new tools that process MSIX packages
* Replace hand-written wrappers for the AppxPackaging COM API which aren't kept up to date with new features

## Scope
| Capability | Priority |
| :---------- | :------- |
| Developers can call the AppxPackaging APIs from multiple languages with automatically-generated projections | Must |
| AppxPackaging APIs follow WinRT conventions (naming, interop with Windows.Foundation/Windows.Storage.Streams types, etc.) | Should |
| Developers can install AppxPackaging as a NuGet package, which contains the API metadata and implementation | Should |
| Consolidate with the [MSIX SDK](https://github.com/microsoft/msix-packaging) for non-Windows 10 platforms | Could |

## Important Notes
AppxPackaging.dll is already distributed as part of the Windows SDK, demonstrating that it's possible to deliver this functionality separately from Windows and downlevel.

**Comment by jamespik** [comment]
Hi Matt, 

We recently added C# Interop wrappers for appxpackaging to the MSIX SDK project.
https://github.com/microsoft/msix-packaging/tree/master/tools/utils/Utils/AppxPackagingInterop

In the near future, these utilities will be published via nuget for easy consumption in other projects.
Hopefully that is sufficient to address your immediate needs.

Longer term, our intention is to move active development of packaging related support to the cross platform msix packaging library in the MSIX SDK Project.  Please file additional feature requests against that project.
We are happy to review community contributions to the project if you would like to accelerate any particular feature. Otherwise, please look forward to future improvements.

For example, it sounds like we should offer c# interop against our cross platform library msix packaging support.
I opened: https://github.com/microsoft/msix-packaging/issues/366

Thanks!
James

**Comment by jonwis** [comment]
Thanks @jamespik !
