### ISSUE TITLE
Question: any guidance on creating bindings from c and other languages?

### ISSUE THREAD

**Issue by carlokok** [microsoft/ProjectReunion#18]
I see there are bindings for JavaScript, rust and c++. What about languages that want to support this that aren't officially supported? Are there ways to use the new apis from c(which all languages can work from) or any info on how it fits together internally?

**Comment by jonwis** [comment]
Ideally we'd like both Project Reunion and the Windows API surface to be _metadata defined_ so we can do projections to any language.  We're planning using MIDL3 / WinMD to define new Project Reunion APIs so that'll snap into the existing projections.  While C++/WinRT is super awesome I'm aware of projects that either cannot use exceptions & C++17 or decide not to.

@kennykerr and @Scottj1s are building out projections - we've heard the request for a "flat C" or "C++ without exceptions" projection before, especially for very low-level components.

Can you create an issue-per-target-language that you're interested in, along with a little sample snippet of what that projection would look like for an API like this:

```c#
runtimeclass StartupTask
{
    static StartupTask[] GetStartupTasks();
    static StartupTask GetById(String taskId);

    StartupTaskState State { get; };
    String TaskId { get; };

    void Disable();
    IAsyncOperation<StartupTaskState> RequestEnableAsync();
}
```

**Comment by carlokok** [comment]
So this was coming from my own languages (RemObjects elements native target). The.midl3 stuff you mentioned will be very useful to me, or really any sample in pure c will already be fantastic.

At some point I looked at the winrt header files, but I had trouble finding good non c++ samples.

**Comment by mdtauk** [comment]
There is the Xlang project which is doing similar things.

It would be useful for non-windows developers to be able to use Swift or Kotlin to make apps.  Maybe even Java and TypeScript - whilst still using XAML for UI

**Comment by jonwis** [comment]
Check out https://docs.microsoft.com/en-us/samples/microsoft/windows-appsample-photo-editor/photo-editor-cwinrt-sample-application/ for a pretty neat complete sample of using C++/WinRT.

While it's not _easy_ to make projections, the tooling in both xlang and the cppwinrt repos can help.    Filing issues in this repo for each language you want projected and then bumping them will help us prioritize!

Just answering my own question, the startup task object could be represented as...

```c
DECLARE_HANDLE(R_AM_STARTUPTASK);
STDAPI StartupTaskGetById(_In_ PCWSTR taskId, _Outptr_ R_AM_STARTUPTASK* result);
STDAPI_(VOID) CloseStartupTask(_In_opt_ R_AM_STARTUPTASK task);
STDAPI GetStartupTaskState(_In_ R_AM_STARTUPTASK task, R_Am_StartupTaskState* state);
STDAPI GetStartupTaskTaskId(_In_ R_AM_STARTUPTASK task, _Outptr_ PWSTR* result);
STDAPI StartupTaskDisable(_In_ R_AM_STARTUPTASK task);
STDAPI StartupTaskRequestEnable(_In_ R_AM_STARTUPTASK task, _Inout_ ReunionAsync* async);
STDAPI StartupTaskRequestGetResult(_In_ ReunionAsync* async, _Out_ R_Am_StartupTaskState*);
```

**Comment by jonwis** [comment]
Also, note that you _can_ use WinMDs and MIDL3 directly from your C code.

1. Right-click the IDL file, Properties
2. Under "MIDL > Output" set the "Header file" to `$(IntDir)\%(FileName).h`
3. Apply settings
4. Add `#include "FileName.h"` to your C code
5. Use the CINTERFACE definitions. `IFoo` is a structure containing a `__x_ABI_CFoo_CIFooVtbl* lpVtbl` with members for each method visible on `IFoo`

This is of course why we like projections - they're easier for you to program against. :)

**Comment by pjmlp** [comment]
@jonwis  Regarding MIDL3, I dearly miss C++/CX when dealing with the lack of tooling currently available. Currently porting one DirectX sample from C++/CX to C++/WinRT is an exercise in masochism.

So it would be nice that in the context of opening binding creation to other language communities there would be some thought in actually making it a painless exercise instead of reviving ATL memories.

**Comment by carlokok** [comment]
Thanks this is all very useful information. I'm going to play with it and see how far I can get.

**Comment by effolkronium** [comment]
Will Win32 be deprecated?

**Comment by jonwis** [comment]
> Will Win32api be deprecated?

No - your app can continue to use Win32 APIs.  Project Reunion brings new unified APIs and new functionality.  We're considering a partitioning of the Windows Kit much like the `_APP` partition to help code that stays within the partition be nearly "Project Reunion Family" ready.
