### ISSUE TITLE
Question: Is it possible to create an out-of-process background task in a Desktop application as is with UWP?

### ISSUE THREAD

**Issue by BrunoBlanes** [microsoft/ProjectReunion#313]
I know UWP uses a Windows Runtime Component which is not compatible with .NET 5, so that made me wonder, how does one go about creating background tasks for Win32 applications using .NET and not .NET Framework?

**Comment by BrunoBlanes** [comment]
Yes it is, I found a tutorial and I had to add a UWP project to the Package.

**Comment by JosHuybrighs** [comment]
@BrunoBlanes , I think the question must be re-opened.

You can indeed add an out-of-process background task by adding a UWP host app to the package, but doing that limits what you can do with the UI on the WPF side. In fact:

- You can't use XamlIslands, since it needs an additional UWP hosting app. The hosting app gets in conflict with the background task hosting app because there are now 2 App.xbf resources.
- You can't use WinUI 3 because of the same conflict with 2 App.xbf files.

See also [Can't make release build with a WPF desktop app that is using Xaml Islands and Background Tasks](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/295), and [Support for Background Tasks in WPF desktop apps (.NET 5 and WinUI 3)](https://docs.microsoft.com/en-us/answers/questions/194950/support-for-background-tasks-in-wpf-desktop-apps-n.html?childToView=195289#comment-195289).

**Comment by BrunoBlanes** [comment]
> You can't use WinUI 3 because of the same conflict with 2 App.xbf files.

@JosHuybrighs a workaround is to rename the `App.xaml` and `App.xaml.cs` on the UWP background project to `Main.xaml` and `Main.xaml.cs` respectively.

**Comment by BrunoBlanes** [comment]
> You can't use XamlIslands, since it needs an additional UWP hosting app. The hosting app gets in conflict with the background task hosting app because there are now 2 App.xbf resources.

In theory you could keep renaming the project entry file to make all of them different from one another, however, I think only `App` and `Main` are allowed. So, if only these two names are allowed by the compiler, you are limited to the main Win32 app and one UWP app in the package.
I am not sure about those naming constrains though, there might be a third one that is allowed by the compiler and I am not aware of it.

**Comment by JosHuybrighs** [comment]
@BrunoBlanes  Thanks for the hints. I tested it in the mean time and it turns out that VS 2019 Prev2 doesn't allow me to rename App.xaml and App.xaml.cs. When building the hosting app it returns:

`1>C:\Users\joshu\Projecten\Software\Eigen\WPFXamlIslandsWithBGTask\UWP.BGHost\UWP.BGHost.csproj : XamlCompiler error WMC1008: Application main file must be named App.xaml`

Some time ago I have also posted my findings on the VS forum. See [Can't make release build with a WPF desktop app that is using Xaml Islands and Background Tasks](https://developercommunity2.visualstudio.com/t/Cant-make-release-build-with-a-WPF-desk/1249246?port=1025&fsid=646dc06f-be24-4842-9b0a-f69c62b43b5d&entry=myfeedback). The reply was more or less: it is not a bug, it is what it is.

My question whether a packaged WPF app that is using WinUI 3 and .NET5 can or will eventually support Background Tasks sadly enough stays unanswered. I don't need it immediately for my app on the Windows Store (SyncFolder) since I am currently using DesktopBridge with a UWP app and a win32 process for all the things UWP is not allowed to do. I am simply hoping that WPF with WinUI 3 and Background Tasks would be possible at some point in time. It would make the architecture much more stable and reliable.

**Comment by BrunoBlanes** [comment]
> `1>C:\Users\joshu\Projecten\Software\Eigen\WPFXamlIslandsWithBGTask\UWP.BGHost\UWP.BGHost.csproj : XamlCompiler error WMC1008: Application main file must be named App.xaml`

Make sure you renamed it to `Main` and do a clean build, delete `obj` and `bin` folders.

> My question whether a packaged WPF app that is using WinUI 3 and .NET5 can or will eventually support Background Tasks sadly enough stays unanswered.

It does through the above method, I have it working on a project of mine. You do however need to download the `Microsoft.Toolkit.Uwp.Notifications` at least version 8.0.0-preview3, which is compatible with WinUI 3 Preview 3.

**Comment by BrunoBlanes** [comment]
I should point out that Xaml Islands is not yet supported on WinUI 3 Preview 3, as stated on its [release notes](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#missing-platform-features).

**Comment by JosHuybrighs** [comment]
Indeed XamlIslands isn't yet supported on WinUI 3. My latest findings with renaming App.xaml/cs to Main.xaml/cs are;

- With a packaged WPF/XamlIsland solution the above error 'Application main file must be named App.xaml' is generated.
- With a packaged WPF/WinUI3 solution te above error does not occur but I get the error:

`7>C:\Users\joshu\Projecten\Software\Eigen\master\SyncFolder\SyncFolder (Package)\bin\x64\Debug\AppxManifest.xml : error APPX0501: Validation error. error 80080204: App manifest validation error: Line 854, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.System.DispatcherQueue" must only be declared once. A duplicate exists on Line 69, Column 27.`

I assume this comes from bringing the background hosting app together with the WPF app. The resulting manifest file (generated by VS) generates a bunch of duplicate entries for InProcessServer. I am not familiar with what is generated in the manifest file but it looks like all the ActivatableClass entries that are generated because of the WPF app are also generated when adding the UWP hosting app.

It seems that something has to be configured in the UWP host project file to tell VS not to generate these duplicates.

**Comment by BrunoBlanes** [comment]
I haven't done anything in this project yet using `InProcessServer`, however I think you are supposed to move those calls to the package project's `appmanifest` file or do you need them on both projects?

**Comment by JosHuybrighs** [comment]
@BrunoBlanes Neither have I. The 3 manifest files in the 3 projects (UWPhost, WPF app, and WPF Package) are the normal manifest files that are created when adding a project and don't contain anything that refers to InProcessServer. The manifest file that is holding these duplicates and for which the error is generated is created by VS when building the package project. The file is stored in the bin\..\debug folder and is called AppxManifest.xml.

**Comment by BrunoBlanes** [comment]
Have you deleted the `bin` and `obj` files from all three projects and rebuilt the solution?

**Comment by JosHuybrighs** [comment]
@BrunoBlanes  Yes. Same error.
I made a completely new test in the mean time with the most basic WPF WinUI 3 app possible and a simple background task.
It shows the same error.
For anyone interested in trying this out the solution is available [here - WPFWinUI3WithBGTask.zip](https://1drv.ms/u/s!AugQvFxkydtIhq53xICOzZNZ_tRl7Q?e=LVYAxN).

**Comment by BrunoBlanes** [comment]
Yeah, might be that I didn't explain it properly, but the `App` class also needs to be renamed to `Main`. I'll see if that's all and let you know.

**Comment by BrunoBlanes** [comment]
Also, your UWP host project will not contain any UI elements, so remove any references to WinUI from it and instead use Windows.UI.Xaml.

**Comment by JosHuybrighs** [comment]
@BrunoBlanes  Can you tell me what kind of VS project template you use to create both the UWP Windows Runtime Component and the UWP Host app?

- Windows.UI.Xaml is what will be included when creating the UWP Host app for a real UWP environment. If I take that as project template VS unfortunately doesn't allow me te rename App.xaml.
- If I take the latest 'Blank App (WinUI in UWP) then the new microsoft namespaces will be used, I can rename App.xaml, but I cannot remove the references to WinUI (unless I start manually editing the project file).

**Comment by BrunoBlanes** [comment]
Ok, I was trying to isolate the steps you'd need to take, so here it goes:

- Rename your `App` class to `Main`, `App.xaml` file to `Main.xaml` and `App.xaml.cs` file to `Main.xaml.cs`.
- Change the inherited `Application` class in your `Main.xaml.cs` from `Microsoft.UI.Xaml` to `Windows.UI.Xaml`.
- In your `Main.xaml` remove all the contents of `<Application>` and make sure its `x:Class` is using `Main` instead of `App`.
- Remove all references to WinUI from the UWP host and runtime projects, those are not your layout. The template adds them if you are building a UWP app which isn't the case, this is a WPF, so we'll be using the default UWP and runtime template.
- Your UWP host and runtime applications must target Windows version `10.0.19041.0`.

If you follow these steps, you'll be able to build the project you linked.

**Comment by JosHuybrighs** [comment]
You are my hero!

Changing the inheritance of `Application` to `Windows.UI.Xaml` and removing all WinUI references did it!

A big thanks for all the effort you took to check the example code. It is encouraging in these polarized and dividing times that there are people who selflessly want to help others.

I will also add the solution to the Q&A forum where I was looking for help ([Support for Background Tasks in WPF desktop apps (.NET 5 and WinUI 3)](https://docs.microsoft.com/en-us/answers/questions/194950/support-for-background-tasks-in-wpf-desktop-apps-n.html?childToView=195289#comment-195289)).

**Comment by BrunoBlanes** [comment]
You are most welcome!

Keep in mind that if you are going to be using Windows notifications, as is configured in your project, you will need to use `Microsoft.Toolkit.Uwp.Notifications` at least version 8.0.0-preview3 on the WPF project to be able to register the background notification service.

You can download that using the [this](https://pkgs.dev.azure.com/dotnet/WindowsCommunityToolkit/_packaging/WindowsCommunityToolkit-WinUI3/nuget/v3/index.json) NuGet package source for WinUI 3 Previews.

There were some great improvements to how notifications work on Win32, so take a look at [this ](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3457 )PR if you haven't already. Basically, it works like it UWP does, no need for all that GUID stuff.
