### ISSUE TITLE
Update nuget.config per latest guidance

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/ProjectReunion#316]
Per latest guidance How to Securely Configure Package Source Files nuget.config should have `<packageSources>` and `<disabledPackageSources>` and start both with `<clear />` 
e.g.
```
<configuration>
    <packageSources>
        <clear />
        ...
    </packageSources>
    <disabledPackageSources>
        <clear />
    </disabledPackageSources>
</configuration>
```

Current nuget.config has no `<disabledPackageSources>`. Add it

**Comment by wjk** [comment]
Just wanted to throw in there that the use of the WindowsES-External NuGet feed is causing me so much grief right now. Since I’m not a Microsoft employee (yet), that feed refuses my credentials. If I cancel the credential dialog, the solution then loads, but I need to remove that NuGet feed from the config file. Once that is done, NuGet gets into a loop where it cannot complete package-restore due to a package only available on that feed, and therefore refuses to do anything (including deleting the troublesome package) until restore has been completed successfully, which will never happen.

To get Visual Studio even close to usable I had to remove the corresponding line from `nuget.config`, and unload the `CppTest` project. Since you are updating this file, I would appreciate it if you took my into issue account. Thanks!
