### ISSUE TITLE
Question: Will this help with modernising MFC apps?

### ISSUE THREAD

**Issue by dylanede** [microsoft/ProjectReunion#33]
I know the readme says 

> Project Reunion will help you update and modernize your existing apps with the latest functionality

but does "existing apps" include MFC ones, or just those using Win32 directly? I'd be very interested in hearing about plans for how to help migration of MFC apps to modern APIs.

**Comment by jonwis** [comment]
Sure, we love all your apps - MFC included!

Initially we're focusing on enabling access to platform functionality in a modernized (and forward looking) way. Let's say your MFC app wants to use #10 (common startup task support) instead of what you might be doing about writing directly into there registry or Shell Startup folder.  You'll be able to bring in enough Project Reunion to light up that startup task functionality and remove your existing MFC-style code.

At least for now, we don't anticipate having "code rewriters" if that's what you're looking for.

Are there specific areas of MFC you're using that you'd like modernized?  Are there parts of the modern API surface that you'd like to use but can't because there's no integration with MFC? Let us know either in this issue thread or by filing specific Feature Request issues with more details!

**Comment by dylanede** [comment]
My initial thoughts were about how to most painlessly migrate MFC apps to WinUI. What plans/ideas do you have for that?

**Comment by jonwis** [comment]
Thanks - I think that's a question best suited for the WinUI repo, as that's the project for UX.  If there are specific non-UX features you're using from MFC please comment here again and we'll help redirect further (or, file a feature proposal!)
