### ISSUE TITLE
WPF + .Net 5 + WinRT APIs cause exceptions when running with elevated privileges.

### ISSUE THREAD

**Issue by Noemata** [microsoft/ProjectReunion#407]
**Describe the bug**
WinRT APIs such as FolderPicker will generate an exception if a WPF application is running with elevated privileges.  Without elevated privileges such APIs execute as expected.

**Steps to reproduce the bug**

Run the following code within a WPF .Net 5 application that has been given elevated privileges through its app.manifest settings.

```
            var folderPicker = new FolderPicker();
            this.InitializeWinRTChild(folderPicker);

            folderPicker.SuggestedStartLocation = PickerLocationId.DocumentsLibrary;
            folderPicker.FileTypeFilter.Add("*");
            var folder = await folderPicker.PickSingleFolderAsync();
```

app.manifest setting

```
<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
```

Note: I did try setting uiAccess to true, same issue

1. Execute the above code.

**Expected behavior**
WinRT APIs should not generate exceptions when running with elevated privileges if those same APIs work as expected without elevated privileges.

**Screenshots**
n/s

**Version Info**
n/a

NuGet package version: 
n/a

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  No  |
| May 2020 Update (19041)            |  No  |
| November 2019 Update (18363)       |  Yes  |
| May 2019 Update (18362)            |  No  |
| October 2018 Update (17763)        |  No  |

**Additional context**
More information should be provided about WinRT API usage under scenarios that are not normally available to a UWP application.

**Comment by andrewleader** [comment]
Thanks for reporting this Noemata! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31582856) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!

If you'd like to track the status of the bug, you could submit this bug report through Feedback Hub and then share your link to your feedback so that I can link it up with the platform bug I created.

**Comment by jonwis** [comment]
For clicky-clicky ease, see http://task.ms/31582856
