### ISSUE TITLE
Question: What reference do I need? The type 'IAsyncAction' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by myokeeh** [microsoft/ProjectReunion#456]
Hopefully, this is a good place for this question.

Context: I just converted a LOB .NET 4.8 WinForms app to .NET 5 using try-convert, and generally, it appears to be working as expected--even to the point that I've been able to submit it to the Store and available to our company via Store for Business.

I've been slowly adding new features into like access to LocalFolder:

```
StorageFile filed = await ApplicationData.Current.LocalFolder.GetFileAsync("store");
```
But getting an error on that line: 

>Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.	APPWF C:\Form.cs	131	Active

I have the `Microsoft.Windows.SDK.Contracts 10.0.19041.1` NuGet package referenced.

I'm unsure what I need to reference in this case. I tried adding `Windows.winmd`, but Visual Studio doesn't allow me to do that--assume it's redundant to `Microsoft.Windows.SDK.Contracts`

Also, I was expecting `<TargetFramework>net5.0-windows</TargetFramework>` and that's how try-convert converted it, but I'm a little confused about needing to change it to `<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>` Is this a temporary thing?

**Comment by andrewleader** [comment]
Hi Carlo, thanks for asking this question! However, as this is an existing Windows platform question, the right place to ask this question would be Microsoft Q&A under the `windows-desktop-bridge` topic: https://docs.microsoft.com/en-us/answers/topics/windows-desktop-bridge.html

But yes, as you said in your post, the correct resolution should be to...

1. Use `<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>` (this automatically includes the Windows 10 SDK)
2. Remove your previous `Microsoft.Windows.SDK.Contracts 10.0.19041.1` NuGet package (since the target framework now includes the Windows 10 SDK)

If you have any further questions on this topic, please post them on Microsoft Q&A!

**Comment by myokeeh** [comment]
@andrewleader Ah! No. 2 worked. I was piecing too many things found online incorrectly.
