### ISSUE TITLE
Main build failure due to missing Microsoft.Taef.10.58.210222006-develop

### ISSUE THREAD

**Issue by riverar** [microsoft/ProjectReunion#492]
Externals don't have access to Taef-develop package

```cmd
C:\Sources\ProjectReunion\test\CppTest\CppTest.vcxproj(342,5):
error : This project references NuGet package(s) that are missing on this computer.
Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105.
The missing file is ..\..\packages\Microsoft.Taef.10.58.210222006-develop\build\Microsoft.Taef.targets.
```

https://github.com/microsoft/ProjectReunion/blob/93e786dc7461e41ddd4afc2476a4d1cf765a6bdd/test/CppTest/CppTest.vcxproj#L342

cc: @kythant

**Comment by BenJKuhn** [comment]
This should be visible on our public-facing ADO feed. 

Can you see this link? I switched to my personal ADO account, and it seems to be working, so you may just need to add that feed to your VS configuration (which also means I may need to fix instructions somewhere).
https://dev.azure.com/ms/ProjectReunion/_packaging?_a=package&feed=ProjectReunion-Dependencies&package=Microsoft.Taef&protocolType=NuGet&version=10.58.210222006-develop

**Comment by kythant** [comment]
This was not because of PR-dependencies feed. This was due to the ExternalES feed I was using. I didn't realize it was not public when I originally did the change. So I pulled the Taef package from there and pushed it to PR-Dependencies. The pull request is out for the fix.
https://github.com/microsoft/ProjectReunion/pull/494
