### ISSUE TITLE
Give packaged desktop apps access to more WinRT APIs

### ISSUE THREAD

**Issue by benstevens48** [microsoft/ProjectReunion#501]
# Proposal: Give packaged desktop apps access to more WinRT APIs

## Summary
This page <https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api> details the WinRT APIs available to packaged desktop apps. However there are quite a few APIs missing that should be able to work. In particular I am interested in being able to use `Windows.System.Profile.SystemIdentification.GetSystemIdForPublisher`. I haven't actually tested whether this works or not (I am currently forward planning). If it already works, then the docs should be updated.

## Rationale
The `Windows.System.Profile.SystemIdentification.GetSystemIdForPublisher` API is the main way for identifying the device in a UWP app (I think) and is very useful for things like device-specific licences or notifications etc. If the publisher produces desktop or UWP variants of an app or a suite of apps, some of which are desktop and some UWP, then it is necessary to be able to call this API from both packaged desktop apps (or perhaps even desktop apps with an identity) and UWP apps.

**Comment by riverar** [comment]
When you don't use the appropriate proposal format, it makes it much harder to read the proposal and understand the need for what you're asking. So now we have to go back/forth on questions.

That said, it sounds like the scenario is: You have a codebase that runs on Windows, both outside and inside AppContainer and want an API to call to determine what context you're in. The pattern for that is calling the `GetCurrentPackageFullName` API and keying off whether or not it returns `APPMODEL_ERROR_NO_PACKAGE`. If writing the P/Invoke code to do so isn't your cup of tea, you can bring in [`DesktopBridge.Helpers`](https://github.com/qmatteoq/DesktopBridgeHelpers/) from Nuget and call its `IsRunningAsUwp` API.

Here's a good rundown of feature detection with API contracts that's worth a read too https://blogs.windows.com/windowsdeveloper/2015/09/15/dynamically-detecting-features-with-api-contracts-10-by-10/

**Comment by benstevens48** [comment]
@riverar - I think you have completely misinterpreted the proposal. It does follow the suggested format, but omitting the optional sections because they weren't really relevant.

I thought the proposal was clear in its simplicity. Simply make as many WinRT APIs as possible available for use within packaged desktop apps. As I mentioned before, there are may APIs missing which ought to be available (using this doc as the source of what's available <https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api>).

The rationale is basically to be able to use the same APIs from desktop and UWP apps (which is the whole point of Project Reunion). One use case for this is being able to create a UWP and packaged desktop version of the same app from almost the same code base. Also ensuring that the app has a future path of becoming either a UWP app or a desktop app depending on how the Windows app development story pans out.

I called out the specific API `Windows.System.Profile.SystemIdentification.GetSystemIdForPublisher` because that's the one I happened to be checking for availability to desktop apps, and there are some additional reasons for wanting this to be available to both types of app, as I mentioned, for example tying a license to a device. For future-proofing, I want to ensure I will be able to call this from a desktop app in the future and get the same result on the same device if the publisher is the same.

**Comment by riverar** [comment]
@benstevens48 Yep, my mistake. I didn't realize those sections were optional. 🙈

I think the proposal scope is too large and just ultimately calls for Project Reunion as the solution. But in the case of the `GetSystemIdForPublisher` API, I just tested it. And _surprisingly_ it works both in an unpackaged desktop application and packaged "UWP" app.

```csharp
var systemIdBytes = SystemIdentification.GetSystemIdForPublisher().Id.ToArray();
Console.WriteLine($"System Id: { BitConverter.ToString(systemIdBytes) }");
```

So I think you're right in that this falls into a documentation issue. (Might also be an SDK bug due to lack of DualApiPartition attribute?) It's not clear [which guarantees apply](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforpublisher?view=winrt-19041#remarks) in these contexts so I'd tread lightly in using it for anything critical.

**Comment by jonwis** [comment]
Sadly, the `[dualapipartition]` metadata marker is non-uniformly applied. Its initial intent was as you suggest, "this API can be called from desktop apps." But then we kept adding APIs without the marker that would perfectly fine in Desktop Bridge (or unpackaged Win32 apps).  There _are_ APIs that need a UWP or package identity, but _many_ of the APIs added in the last 2-ish releases (since UniversalApiContract 8 or so) are "identity transparent" in that they work in packaged & unpackaged & full-trust & partial-trust with appropriate fallback.

The https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api list of supported APIs with package identity sure looks inaccurate - `Windows.Foundation.AsyncActionCompletedHandler` is a super low level delegate type that doesn't care about packaged or trust level.  I've asked @AdamBraden to take a look.

For the specific advertising ID question, the UWP API uses publisher identity so each publisher gets a unique identifier for system on which it's running.  For unpackaged apps, this likely produces the same value for all apps without identity on a system.  Check out a simple snippet that works in an unpackaged app built by Visual Studio:

```c++
#include <winrt/Windows.System.Profile.h>
#include <winrt/Windows.Security.Cryptography.h>

auto id = winrt::Windows::System::Profile::SystemIdentification::GetSystemIdForPublisher();
auto val = winrt::Windows::Security::Cryptography::CryptographicBuffer::EncodeToBase64String(id.Id());
auto raw = val.c_str();
std::wcout << raw << std::endl;
```

**Comment by benstevens48** [comment]
@riverar and @jonwis  - thanks for testing it! Really what I need to do is test it in a packaged desktop app to check if I get the same value as with a UWP app with the same publisher name. I just haven't got around to investigating the whole app packaging project machinery yet.

@jonwis or other Project Union maintainers - what do you think I should do with this issue? Should it become an issue about ensuring the docs are up-to-date with regards to what APIs can be called from desktop apps? Should it focus just on documenting or ensuring the correct behavior of the single GetSystemIdForPublisher API that I mentioned (or maybe I should open a separate issue for that)? Or should it stay as it is in case there are APIs that really aren't callable from desktop at the moment but should be?

**Comment by andrewleader** [comment]
Thanks @benstevens48, it seems like our team has consensus that our docs are out-of-date around which APIs work for desktop apps vs UWP.

Currently, all of that is part of the Windows Developer Platform, whereas Project Reunion is focused on a set of APIs that ship out-of-band. Project Reunion is focused on addressing these inconsistencies across desktop and UWP with a common set of APIs, but for existing APIs, we are tracking that with our existing internal bug systems.

Therefore, I'll go ahead and close this issue to keep this repo focused on Project Reunion since we already have this tracked internally and Adam Braden from our team will be working on ensuring our docs are updated. I wish we had a place to track platform issues publicly, but we currently don't. Feel free to ping this thread for updates though.

**Comment by benstevens48** [comment]
@andrewleader - thanks. I'd just like to emphasize that updating the docs is important because otherwise we don't know if we can use APIs reliably or not, as per this quote from the [docs](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api) regarding which WinRT APIs are supported from desktop.
> Occasionally, APIs in these areas may appear to function correctly. However, if an API is not explicitly listed as supported, you should avoid using it as it may have unintended side effects or behavior. Support for these APIs may become available in future releases. In the interim, your app should use relevant Win32 or .NET APIs instead.

I appreciate that you are not shipping these APIs as part of the Project Reunion package, however, being able to reliably call these APIs from a desktop app (including knowing what the minimum required version of Windows 10 is, separately from the minimum version required for UWP), is a key part of Project Reunion in the more general sense, i.e. unifying the code which we use to write Windows apps.

Also, if the APIs are not supported then it seems legitimate to submit a suggestion that Project Reunion should provide an equivalent API (on a case-by-case basis, but this requires the docs to be up-to-date first).

**Comment by andrewleader** [comment]
Fully agreed - And to your last point, if you do find an API that actually is not supported, please do submit a suggestion that Project Reunion should provide an equivalent supported API so we know where to prioritize!

**Comment by riverar** [comment]
So while this is all still fresh in our heads, in the short term can we at least get @benstevens48 an answer on whether or not this API is safe for desktop use? If so, [which guarantees can they rely on](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforpublisher?view=winrt-19041#remarks)?

**Comment by jonwis** [comment]
This API is safe for desktop use, with the caveat that every app without publisher identity will get the same advertising ID.
