### ISSUE TITLE
Is there a glossary somewhere? New minds are overwhelmed.

### ISSUE THREAD

**Issue by alphahorse** [microsoft/ProjectReunion#51]
For people coming here who have no experience with Project Reunion, many of the threads may contain too much jargon to be very useful. Don't get me wrong - jargon has its place, as a compact way of expressing commonly-understood terms and concepts, but the key point here is "commonly-understood". In a quick scan through some initial threads, I saw many terms I didn't recognize; some I was able work out, some I found via old man google, but others are less clear: as an example, the use of the word "projection" as it appears here is unfamiliar to me, and I'm not sure that the meaning I've assigned to it is correct.

Normally, I would expect to find things that I, as a new arrival, might not understand in the FAQ, but to be honest, the FAQ is currently very, um, "sparse", and itself rather thick with unfamiliar terms. My request would be that someone put together a basic glossary of terminology and link it from the FAQ. This would certainly help me, and I'm sure would help other new arrivals as well - people who might otherwise be put off and leave.

I'd be happy to be a newbie guinea-pig and compile a short list of terms that could be usefully clarified if someone asks me to.

**Comment by ShankarBUS** [comment]
> "projection"

Do you mean language projection such as C#/WinRT, C++/WinRT, etc.?

If so, "projection" means the binding of APIs between different runtimes (WinRT, .NET, JS, RUST, etc.).

For example, C#/WinRT is just a wrapper around WinRT for C# language i.e C#/.NET <--> C#/WinRT <--> WinRT

Reference : [C#/WinRT](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/)

**Comment by jonwis** [comment]
@alphahorse  - please do add a comment with the set of terms you're interested in!  @mevey  or I will be happy to put together an update to the FAQ (or a new GLOSSARY.md) with them.

**Comment by KyleNanakdewa** [comment]
Adding onto this, I think it could be very helpful to have a sort of "quick start" to help both those who are new altogether, and those who may not be 100% familiar with all the terminology and concepts used.

TypeScript does a fantastic job of this IMO, they have a brand new website that outlines exactly what TypeScript is, and how to get started, whether you are new to programming, or coming from another language like JavaScript, Java, or C#. https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html

I think this could be a good model for Project Reunion. There's been numerous issues in both this repo (#17 #30 #36 #40 #53) and some others (MAUI [#47](https://github.com/dotnet/maui/issues/47) [#122](https://github.com/dotnet/maui/issues/122)) expressing confusion, and a lot of questions about how things relate to each other. A "get started" guide like how TypeScript has could be a good way to get everyone on the same page, no matter what background they come from.

Something structured like this basically:

- Project Reunion for new programmers and/or students
  - What is Win32 (pros and cons)
  - What is UWP (pros and cons)
  - How Project Reunion unites them under a single platform
  - Quick explanation of C++ vs .NET (WPF/Forms/UWP) vs React/JS, how you can use any one to develop for Windows
    - Links off to other tutorials, like [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/)
    - Needs to be clear that Project Reunion is not a way to develop apps - aka "go develop these somewhere else, then come back and read the appropriate next section to learn how to take advantage of Project Reunion" - as this seems like an easy point of confusion

- Project Reunion for Win32 developers
  - What is Project Reunion
  - What components are available, how they can be useful, etc...

- Project Reunion for UWP developers
  - What is Project Reunion
  - Migrating to WinUI
  - Migrating to .NET 5? (answers to questions in #17 #40 #53)
  - ??? (does Project Reunion bring anything new to UWP devs? future plans here?)

- Project Reunion for React developers
  - What is Project Reunion
  - Bringing apps to Windows
  - Using new components, how they can be useful, etc...

That's just a quick skeleton off the top of my head - I'm not sure how much of this is actually feasible, and it doesn't necessarily need to be full articles like TS has, but I think a tailored approach would definitely be a good way to go.

Best to separate out students, UWP fans, longtime Windows developers, and developers from other platforms, since from my experiences in a couple of MS repos here, these are very different groups, with different needs.

**Comment by stevewri** [comment]
@mevey can you take point? Several of us could collaborate on the content.

**Comment by mevey** [comment]
I've started a [Glossary wiki page](https://github.com/microsoft/ProjectReunion/wiki/Glossary ) that we will develop more.
@KyleNanakdewa You make some great suggestions and we are working to make sure that the docs, FAQ and Glossary can be informative for all categories of Windows developers.
