### ISSUE TITLE
Winui3.0 Desktop + UWP Maui

### ISSUE THREAD

**Issue by Pinox** [microsoft/ProjectReunion#61]
It would be nice to see Winui3.0 Desktop + UWP also join the ranks of the xamarin maui project to use one project for various project deployments.   In my own project WinUI3.0 Desktop + UWP + Blazor would be an awesome combination as the source code are essentially the same except for the respective "views + configuration".

At the very least there should be WinUI3.0 Desktop + UWP.

![Winui3 0](https://user-images.githubusercontent.com/5297255/83788880-32742880-a696-11ea-89a9-5b89fbf468f2.png)

**Comment by michael-hawker** [comment]
🦙 Cross-linking to [MAUI issue](https://github.com/dotnet/maui/issues/70).

**Comment by maxkatz6** [comment]
Isn't it dotnet project system's new feature, not MAUI's itself?

**Comment by BenJKuhn** [comment]
This reminds me a lot of the Windows 8.1 "universal" apps that supported phone and desktop. The configuration was very similar, with some shared and some forked files. This would be an ask on Visual Studio, rather than on project reunion. It might be possible to put together such a project today (though with a lot of rough edges around designer experience, etc.). Making a great "dual-headed" experience in Visual Studio is a major undertaking, especially when you try to generalize it and add deep tooling support.

Unfortunately, this is a long winded way of saying we have no plans on investing in the foreseeable future. As slick as this would be, we have our hands full just making sure that Project Reunion and WinUI are a great experience without adding in other complexities at this time.

**Comment by michael-hawker** [comment]
@BenJKuhn I understand that ultimately supports needs to be in the tooling and Visual Studio for this to work.

I believe the point of this issue is to ensure that _when_ those types of changes occur in the platform that WinUI is brought along with them as a first-class citizen to be compatible with those modifications instead of an afterthought.

That way developers can take advantage to split out code that may differ between Desktop and UWP environments leveraging this type of system. Of course, I believe part of the point of Reunion should be that these types of differences aren't needed as much, right?

All that to say, hopefully your team is involved in the discussions of the work being done to tooling in general for the future.

**Comment by BenJKuhn** [comment]
That's right. Without making any specific promises above my pay grade, the general arc of Windows application model changes over the last few years, which continues with Project Reunion, is to remove the distinction between desktop and UWP as two separate worlds. Apps that can run in appcontainer using the "app as a service" model will have certain advantages around security management, power, as they relate to those features, but the goal is to make each aspect a feature that can be adopted "a-la-carte" rather than treating desktop & UWP apps as two fundamentally separate application models.

There's a lot of work to do on the tooling side, and a lot of potential to deliver some really great experiences. I'm looking forward to being a part of it.
