### ISSUE TITLE
System.Diagnostics: "The specified executable is not a valid application for this OS platform.'"

### ISSUE THREAD

**Issue by wandtke** [microsoft/ProjectReunion#871]
**Describe the bug**
When trying to open a .lnk file I am given this exception even though .exe files work fine.
Full Error: System.ComponentModel.Win32Exception: 'The specified executable is not a valid application for this OS platform.'

**Steps to reproduce the bug**
Use Process.start("*path to .lnk");
Error is thrown.

**Expected behavior**
Launching the shortcut file.

**Version Info**
Windows 10 20H2

NuGet package version: 
Project Reunion 0.5.7

**Comment by riverar** [comment]
This is expected behavior because the .lnk file you specified is not a valid application, and the version of .NET you're using (presumably .NET 5) does not pass off the request to the shell. [(`UseShellExecute` defaults changed after .NET Framework was released.)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=net-5.0&WT.mc_id=WD-MVP-5002756)

When using this API, you can use the overload that accepts a [`ProcessStartInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=net-5.0&WT.mc_id=WD-MVP-5002756#System_Diagnostics_Process_Start_System_Diagnostics_ProcessStartInfo_) to explicitly specify the desired hand-off behavior.

Example:
```csharp
Process.Start(new ProcessStartInfo { FileName = "my.lnk", UseShellExecute = true });
```

**Comment by andrewleader** [comment]
Thanks for answering Rafael! Closing as inactive and hopefully resolved.
